// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncMessage.proto

package com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf;

public final class SyncMessageProtobuf {
  private SyncMessageProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SyncMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:myfootprints.SyncMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string operationType = 1;</code>
     */
    boolean hasOperationType();
    /**
     * <code>required string operationType = 1;</code>
     */
    java.lang.String getOperationType();
    /**
     * <code>required string operationType = 1;</code>
     */
    com.google.protobuf.ByteString
        getOperationTypeBytes();

    /**
     * <code>required int32 entityType = 2;</code>
     */
    boolean hasEntityType();
    /**
     * <code>required int32 entityType = 2;</code>
     */
    int getEntityType();

    /**
     * <code>required string entityUid = 3;</code>
     */
    boolean hasEntityUid();
    /**
     * <code>required string entityUid = 3;</code>
     */
    java.lang.String getEntityUid();
    /**
     * <code>required string entityUid = 3;</code>
     */
    com.google.protobuf.ByteString
        getEntityUidBytes();

    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    java.util.List<java.lang.String>
        getFieldStrList();
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    int getFieldStrCount();
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    java.lang.String getFieldStr(int index);
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    com.google.protobuf.ByteString
        getFieldStrBytes(int index);

    /**
     * <code>repeated string valueStr = 5;</code>
     */
    java.util.List<java.lang.String>
        getValueStrList();
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    int getValueStrCount();
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    java.lang.String getValueStr(int index);
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueStrBytes(int index);

    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    java.util.List<java.lang.String>
        getFieldBinList();
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    int getFieldBinCount();
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    java.lang.String getFieldBin(int index);
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    com.google.protobuf.ByteString
        getFieldBinBytes(int index);

    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getValueBinList();
    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    int getValueBinCount();
    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    com.google.protobuf.ByteString getValueBin(int index);
  }
  /**
   * Protobuf type {@code myfootprints.SyncMessage}
   */
  public  static final class SyncMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:myfootprints.SyncMessage)
      SyncMessageOrBuilder {
    // Use SyncMessage.newBuilder() to construct.
    private SyncMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SyncMessage() {
      operationType_ = "";
      entityType_ = 0;
      entityUid_ = "";
      fieldStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      valueStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldBin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      valueBin_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SyncMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              operationType_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              entityType_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              entityUid_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fieldStr_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              fieldStr_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                valueStr_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              valueStr_.add(bs);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                fieldBin_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              fieldBin_.add(bs);
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                valueBin_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000040;
              }
              valueBin_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStr_ = fieldStr_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          valueStr_ = valueStr_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          fieldBin_ = fieldBin_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          valueBin_ = java.util.Collections.unmodifiableList(valueBin_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.internal_static_myfootprints_SyncMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.internal_static_myfootprints_SyncMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.class, com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.Builder.class);
    }

    private int bitField0_;
    public static final int OPERATIONTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object operationType_;
    /**
     * <code>required string operationType = 1;</code>
     */
    public boolean hasOperationType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string operationType = 1;</code>
     */
    public java.lang.String getOperationType() {
      java.lang.Object ref = operationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operationType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string operationType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperationTypeBytes() {
      java.lang.Object ref = operationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTITYTYPE_FIELD_NUMBER = 2;
    private int entityType_;
    /**
     * <code>required int32 entityType = 2;</code>
     */
    public boolean hasEntityType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 entityType = 2;</code>
     */
    public int getEntityType() {
      return entityType_;
    }

    public static final int ENTITYUID_FIELD_NUMBER = 3;
    private volatile java.lang.Object entityUid_;
    /**
     * <code>required string entityUid = 3;</code>
     */
    public boolean hasEntityUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string entityUid = 3;</code>
     */
    public java.lang.String getEntityUid() {
      java.lang.Object ref = entityUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entityUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string entityUid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEntityUidBytes() {
      java.lang.Object ref = entityUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDSTR_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList fieldStr_;
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldStrList() {
      return fieldStr_;
    }
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    public int getFieldStrCount() {
      return fieldStr_.size();
    }
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    public java.lang.String getFieldStr(int index) {
      return fieldStr_.get(index);
    }
    /**
     * <code>repeated string fieldStr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFieldStrBytes(int index) {
      return fieldStr_.getByteString(index);
    }

    public static final int VALUESTR_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList valueStr_;
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValueStrList() {
      return valueStr_;
    }
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    public int getValueStrCount() {
      return valueStr_.size();
    }
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    public java.lang.String getValueStr(int index) {
      return valueStr_.get(index);
    }
    /**
     * <code>repeated string valueStr = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueStrBytes(int index) {
      return valueStr_.getByteString(index);
    }

    public static final int FIELDBIN_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList fieldBin_;
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldBinList() {
      return fieldBin_;
    }
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    public int getFieldBinCount() {
      return fieldBin_.size();
    }
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    public java.lang.String getFieldBin(int index) {
      return fieldBin_.get(index);
    }
    /**
     * <code>repeated string fieldBin = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFieldBinBytes(int index) {
      return fieldBin_.getByteString(index);
    }

    public static final int VALUEBIN_FIELD_NUMBER = 7;
    private java.util.List<com.google.protobuf.ByteString> valueBin_;
    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getValueBinList() {
      return valueBin_;
    }
    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    public int getValueBinCount() {
      return valueBin_.size();
    }
    /**
     * <code>repeated bytes valueBin = 7;</code>
     */
    public com.google.protobuf.ByteString getValueBin(int index) {
      return valueBin_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOperationType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntityType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEntityUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operationType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, entityType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, entityUid_);
      }
      for (int i = 0; i < fieldStr_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fieldStr_.getRaw(i));
      }
      for (int i = 0; i < valueStr_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, valueStr_.getRaw(i));
      }
      for (int i = 0; i < fieldBin_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fieldBin_.getRaw(i));
      }
      for (int i = 0; i < valueBin_.size(); i++) {
        output.writeBytes(7, valueBin_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operationType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, entityType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, entityUid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldStr_.size(); i++) {
          dataSize += computeStringSizeNoTag(fieldStr_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFieldStrList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < valueStr_.size(); i++) {
          dataSize += computeStringSizeNoTag(valueStr_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValueStrList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldBin_.size(); i++) {
          dataSize += computeStringSizeNoTag(fieldBin_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFieldBinList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < valueBin_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(valueBin_.get(i));
        }
        size += dataSize;
        size += 1 * getValueBinList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage)) {
        return super.equals(obj);
      }
      com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage other = (com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage) obj;

      boolean result = true;
      result = result && (hasOperationType() == other.hasOperationType());
      if (hasOperationType()) {
        result = result && getOperationType()
            .equals(other.getOperationType());
      }
      result = result && (hasEntityType() == other.hasEntityType());
      if (hasEntityType()) {
        result = result && (getEntityType()
            == other.getEntityType());
      }
      result = result && (hasEntityUid() == other.hasEntityUid());
      if (hasEntityUid()) {
        result = result && getEntityUid()
            .equals(other.getEntityUid());
      }
      result = result && getFieldStrList()
          .equals(other.getFieldStrList());
      result = result && getValueStrList()
          .equals(other.getValueStrList());
      result = result && getFieldBinList()
          .equals(other.getFieldBinList());
      result = result && getValueBinList()
          .equals(other.getValueBinList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOperationType()) {
        hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOperationType().hashCode();
      }
      if (hasEntityType()) {
        hash = (37 * hash) + ENTITYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getEntityType();
      }
      if (hasEntityUid()) {
        hash = (37 * hash) + ENTITYUID_FIELD_NUMBER;
        hash = (53 * hash) + getEntityUid().hashCode();
      }
      if (getFieldStrCount() > 0) {
        hash = (37 * hash) + FIELDSTR_FIELD_NUMBER;
        hash = (53 * hash) + getFieldStrList().hashCode();
      }
      if (getValueStrCount() > 0) {
        hash = (37 * hash) + VALUESTR_FIELD_NUMBER;
        hash = (53 * hash) + getValueStrList().hashCode();
      }
      if (getFieldBinCount() > 0) {
        hash = (37 * hash) + FIELDBIN_FIELD_NUMBER;
        hash = (53 * hash) + getFieldBinList().hashCode();
      }
      if (getValueBinCount() > 0) {
        hash = (37 * hash) + VALUEBIN_FIELD_NUMBER;
        hash = (53 * hash) + getValueBinList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code myfootprints.SyncMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:myfootprints.SyncMessage)
        com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.internal_static_myfootprints_SyncMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.internal_static_myfootprints_SyncMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.class, com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.Builder.class);
      }

      // Construct using com.syleiman.myfootprints.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operationType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        entityType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        entityUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        valueStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        fieldBin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        valueBin_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.internal_static_myfootprints_SyncMessage_descriptor;
      }

      public com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage getDefaultInstanceForType() {
        return com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.getDefaultInstance();
      }

      public com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage build() {
        com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage buildPartial() {
        com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage result = new com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operationType_ = operationType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.entityType_ = entityType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.entityUid_ = entityUid_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStr_ = fieldStr_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fieldStr_ = fieldStr_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          valueStr_ = valueStr_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.valueStr_ = valueStr_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          fieldBin_ = fieldBin_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.fieldBin_ = fieldBin_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          valueBin_ = java.util.Collections.unmodifiableList(valueBin_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.valueBin_ = valueBin_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage) {
          return mergeFrom((com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage other) {
        if (other == com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage.getDefaultInstance()) return this;
        if (other.hasOperationType()) {
          bitField0_ |= 0x00000001;
          operationType_ = other.operationType_;
          onChanged();
        }
        if (other.hasEntityType()) {
          setEntityType(other.getEntityType());
        }
        if (other.hasEntityUid()) {
          bitField0_ |= 0x00000004;
          entityUid_ = other.entityUid_;
          onChanged();
        }
        if (!other.fieldStr_.isEmpty()) {
          if (fieldStr_.isEmpty()) {
            fieldStr_ = other.fieldStr_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFieldStrIsMutable();
            fieldStr_.addAll(other.fieldStr_);
          }
          onChanged();
        }
        if (!other.valueStr_.isEmpty()) {
          if (valueStr_.isEmpty()) {
            valueStr_ = other.valueStr_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureValueStrIsMutable();
            valueStr_.addAll(other.valueStr_);
          }
          onChanged();
        }
        if (!other.fieldBin_.isEmpty()) {
          if (fieldBin_.isEmpty()) {
            fieldBin_ = other.fieldBin_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureFieldBinIsMutable();
            fieldBin_.addAll(other.fieldBin_);
          }
          onChanged();
        }
        if (!other.valueBin_.isEmpty()) {
          if (valueBin_.isEmpty()) {
            valueBin_ = other.valueBin_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureValueBinIsMutable();
            valueBin_.addAll(other.valueBin_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOperationType()) {
          return false;
        }
        if (!hasEntityType()) {
          return false;
        }
        if (!hasEntityUid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object operationType_ = "";
      /**
       * <code>required string operationType = 1;</code>
       */
      public boolean hasOperationType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string operationType = 1;</code>
       */
      public java.lang.String getOperationType() {
        java.lang.Object ref = operationType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            operationType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string operationType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOperationTypeBytes() {
        java.lang.Object ref = operationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string operationType = 1;</code>
       */
      public Builder setOperationType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        operationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string operationType = 1;</code>
       */
      public Builder clearOperationType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operationType_ = getDefaultInstance().getOperationType();
        onChanged();
        return this;
      }
      /**
       * <code>required string operationType = 1;</code>
       */
      public Builder setOperationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        operationType_ = value;
        onChanged();
        return this;
      }

      private int entityType_ ;
      /**
       * <code>required int32 entityType = 2;</code>
       */
      public boolean hasEntityType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 entityType = 2;</code>
       */
      public int getEntityType() {
        return entityType_;
      }
      /**
       * <code>required int32 entityType = 2;</code>
       */
      public Builder setEntityType(int value) {
        bitField0_ |= 0x00000002;
        entityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 entityType = 2;</code>
       */
      public Builder clearEntityType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entityType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object entityUid_ = "";
      /**
       * <code>required string entityUid = 3;</code>
       */
      public boolean hasEntityUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string entityUid = 3;</code>
       */
      public java.lang.String getEntityUid() {
        java.lang.Object ref = entityUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityUid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string entityUid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEntityUidBytes() {
        java.lang.Object ref = entityUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string entityUid = 3;</code>
       */
      public Builder setEntityUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        entityUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string entityUid = 3;</code>
       */
      public Builder clearEntityUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        entityUid_ = getDefaultInstance().getEntityUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string entityUid = 3;</code>
       */
      public Builder setEntityUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        entityUid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fieldStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldStrIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldStr_ = new com.google.protobuf.LazyStringArrayList(fieldStr_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldStrList() {
        return fieldStr_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public int getFieldStrCount() {
        return fieldStr_.size();
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public java.lang.String getFieldStr(int index) {
        return fieldStr_.get(index);
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFieldStrBytes(int index) {
        return fieldStr_.getByteString(index);
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public Builder setFieldStr(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStrIsMutable();
        fieldStr_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public Builder addFieldStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStrIsMutable();
        fieldStr_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public Builder addAllFieldStr(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldStrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldStr_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public Builder clearFieldStr() {
        fieldStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldStr = 4;</code>
       */
      public Builder addFieldStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldStrIsMutable();
        fieldStr_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList valueStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValueStrIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          valueStr_ = new com.google.protobuf.LazyStringArrayList(valueStr_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValueStrList() {
        return valueStr_.getUnmodifiableView();
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public int getValueStrCount() {
        return valueStr_.size();
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public java.lang.String getValueStr(int index) {
        return valueStr_.get(index);
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueStrBytes(int index) {
        return valueStr_.getByteString(index);
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public Builder setValueStr(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueStrIsMutable();
        valueStr_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public Builder addValueStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueStrIsMutable();
        valueStr_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public Builder addAllValueStr(
          java.lang.Iterable<java.lang.String> values) {
        ensureValueStrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, valueStr_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public Builder clearValueStr() {
        valueStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string valueStr = 5;</code>
       */
      public Builder addValueStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueStrIsMutable();
        valueStr_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fieldBin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldBinIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          fieldBin_ = new com.google.protobuf.LazyStringArrayList(fieldBin_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldBinList() {
        return fieldBin_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public int getFieldBinCount() {
        return fieldBin_.size();
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public java.lang.String getFieldBin(int index) {
        return fieldBin_.get(index);
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFieldBinBytes(int index) {
        return fieldBin_.getByteString(index);
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public Builder setFieldBin(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldBinIsMutable();
        fieldBin_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public Builder addFieldBin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldBinIsMutable();
        fieldBin_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public Builder addAllFieldBin(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldBinIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldBin_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public Builder clearFieldBin() {
        fieldBin_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fieldBin = 6;</code>
       */
      public Builder addFieldBinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldBinIsMutable();
        fieldBin_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> valueBin_ = java.util.Collections.emptyList();
      private void ensureValueBinIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          valueBin_ = new java.util.ArrayList<com.google.protobuf.ByteString>(valueBin_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getValueBinList() {
        return java.util.Collections.unmodifiableList(valueBin_);
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public int getValueBinCount() {
        return valueBin_.size();
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public com.google.protobuf.ByteString getValueBin(int index) {
        return valueBin_.get(index);
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public Builder setValueBin(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueBinIsMutable();
        valueBin_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public Builder addValueBin(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValueBinIsMutable();
        valueBin_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public Builder addAllValueBin(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureValueBinIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, valueBin_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes valueBin = 7;</code>
       */
      public Builder clearValueBin() {
        valueBin_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:myfootprints.SyncMessage)
    }

    // @@protoc_insertion_point(class_scope:myfootprints.SyncMessage)
    private static final com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage();
    }

    public static com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SyncMessage>
        PARSER = new com.google.protobuf.AbstractParser<SyncMessage>() {
      public SyncMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SyncMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SyncMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncMessage> getParserForType() {
      return PARSER;
    }

    public com.syleiman.myfootprints.applicationLayer.services.sync.sync.commands.googleDriveSync.transitions.protobuf.SyncMessageProtobuf.SyncMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myfootprints_SyncMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myfootprints_SyncMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021syncMessage.proto\022\014myfootprints\"\223\001\n\013Sy" +
      "ncMessage\022\025\n\roperationType\030\001 \002(\t\022\022\n\nenti" +
      "tyType\030\002 \002(\005\022\021\n\tentityUid\030\003 \002(\t\022\020\n\010field" +
      "Str\030\004 \003(\t\022\020\n\010valueStr\030\005 \003(\t\022\020\n\010fieldBin\030" +
      "\006 \003(\t\022\020\n\010valueBin\030\007 \003(\014Bq\nZcom.syleiman." +
      "myfootprints.services.sync.sync.commands" +
      ".googleDriveSync.transitions.protobufB\023S" +
      "yncMessageProtobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_myfootprints_SyncMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_myfootprints_SyncMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myfootprints_SyncMessage_descriptor,
        new java.lang.String[] { "OperationType", "EntityType", "EntityUid", "FieldStr", "ValueStr", "FieldBin", "ValueBin", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
